"""followers

Revision ID: 039b4fbb5c7b
Revises: aa7e334d3a0d
Create Date: 2019-09-29 17:05:53.963574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '039b4fbb5c7b'
down_revision = 'aa7e334d3a0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
